FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . /app

RUN uv pip install --system -e .
RUN uv pip install --system dependency-injector>=4.46.0

WORKDIR /app/tests/functionals

CMD ["python", "main.py"]