name: Check Integration

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    name: 🧹 Lint (Ubuntu + Python 3.12)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set up Python 3.12
      uses: astral-sh/setup-uv@v5
      with:
        python-version: "3.12"
    - name: Install the project
      run: uv sync --locked --all-extras --all-groups
    - name: Run isort
      run: uv run isort .
    - name: Run flake8
      run: uv run flake8 .
    - name: Run ruff
      run: uv run ruff check .

  test:
    name: 🧪 Tests on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Install uv and set up Python
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project
      run: uv sync --locked --all-extras --all-groups
    - name: Run tests
      run: uv run pytest tests
